### ISSUE TITLE
[Feature] -  Implement Expense Tracking

### ISSUE THREAD

**Issue by tshegofatsoseane** [DrivenIIDevelop/Digital-Dynasty#14]
Implement the below features for Expense Tracking

- [x] **1. Expenses Database Model**
Description: Define the database model for expenses, to store information such as expense category, amount, and date.

- [x] **2. Expenses Controller logic**
Description: Implement the controller logic for creating new expenses, updating existing expenses, and listing expenses, including fetching expense data from the database and filtering by criteria such as category or date.

- [x] **3. Expenses endpoints**
Description: Create API endpoints e.g. (/expenses/) in the expense routes. These endpoints will create, update, and retrieve and return expense data based on specified criteria to the client.

- [x] **4. Testing - Unit Tests**
Description: Write unit tests to ensure that the controller logic for creating and updating, as well as listing all expenses is functioning correctly. Test cases should cover scenarios such as fetching expenses with filters and handling errors.
