### ISSUE TITLE
[Feature] - Implement Payment Tracking

### ISSUE THREAD

**Issue by tshegofatsoseane** [DrivenIIDevelop/Digital-Dynasty#15]
Implement the below features for Payment Tracking

- [x] **1. Payments Database Model**
Description: Define the database model for payments, to store information such as payment method, amount, and date.

- [x] **2. Payments Controller logic**
Description: Implement the controller logic for recording new payments, updating existing payments, and listing all payments, including fetching payment data from the database and sorting by criteria such as amount or date.

- [x] **3. Payments endpoint**
Description: Create an API endpoint (/payments/) in the payments routes to create, update, and list all payments. These endpoints will create, retrieve, and return payment data based on specified criteria to the client.

- [x] **4. Testing - Unit Tests**
Description: Write unit tests to ensure that the controller logic for creating, and listing all payments is functioning correctly. Test cases should cover scenarios such as fetching payments with sorting and handling errors.
